name: Publish on CurseForge & Modrinth

on: [ workflow_dispatch ]

env:
  MINECRAFT_VERSION: 1.21.1
  JAVA_VERSION: 21
  VERSION: 1.21.1-10.1.23
  RELEASE_NAME_CURSEFORGE: "travelersbackpack-neoforge-1.21.1-10.1.23"
  RELEASE_NAME_MODRINTH: "[1.21.1] Traveler's Backpack 10.1.23"
  MODRINTH_TOKEN: ${{ secrets.MODRINTH }}
  CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE }}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 21

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build

      - name: Publish (CurseForge/Modrinth)
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          curseforge-id: 321117
          modrinth-id: rlloIFEV

          curseforge-token: "${{ env.CURSEFORGE_TOKEN }}"
          modrinth-token: "${{ env.MODRINTH_TOKEN }}"

          modrinth-name: ${{ env.RELEASE_NAME_MODRINTH }}
          curseforge-name: ${{ env.RELEASE_NAME_CURSEFORGE }}
          version: "${{ env.VERSION }}"
          version-type: release
          changelog-file: CHANGELOG.md

          loaders: neoforge
          game-versions: "${{ env.MINECRAFT_VERSION }}"
          dependencies: |
            curios-api(optional){modrinth:vvuO3ImH}{curseforge:309927}
            accessories(optional){modrinth:jtmvUHXj}{curseforge:938917}
            polymorph(optional){modrinth:tagwiZkJ}{curseforge:388800}
            comforts(optional){modrinth:SaCpeal4}{curseforge:276951}
            jei(optional){modrinth:u6dRKJwZ}{curseforge:238222}
            rei(optional){modrinth:nfn13YXA}{curseforge:310111}
            emi(optional){modrinth:fRiHVvU7}{curseforge:580555}

          java: "${{ env.JAVA_VERSION }}"